services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\LocaleTools\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'